-- =============================================================================
-- SMS SENTINEL — SUPABASE POSTGRESQL PRODUCTION DATABASE SCHEMA
-- =============================================================================
-- Execute this script in the Supabase SQL Editor (https://supabase.com/dashboard)
-- to create all required tables, constraints, foreign keys, and indexes.
-- Compatible with PostgreSQL 14, 15, 16, and Supabase Postgres.
-- =============================================================================

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast case-insensitive email lookup
CREATE INDEX IF NOT EXISTS idx_users_email ON users (LOWER(email));

-- 2. OAuth Identities Table (Multi-Provider Social Account Linking)
CREATE TABLE IF NOT EXISTS oauth_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider TEXT NOT NULL,
    provider_user_id TEXT NOT NULL,
    email TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_login_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (provider, provider_user_id)
);

-- Indexes for fast identity resolution and user association
CREATE INDEX IF NOT EXISTS idx_oauth_identities_user_id ON oauth_identities (user_id);
CREATE INDEX IF NOT EXISTS idx_oauth_identities_lookup ON oauth_identities (provider, provider_user_id);

-- 3. Analyses Table (Complete Threat Intelligence & SMS Scan Records)
CREATE TABLE IF NOT EXISTS analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    prediction TEXT NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    threat_score INTEGER NOT NULL,
    threat_level TEXT NOT NULL,
    is_spam INTEGER NOT NULL,
    risk_signals JSONB DEFAULT '[]'::jsonb,
    message_stats JSONB DEFAULT '{}'::jsonb,
    highlight_terms JSONB DEFAULT '[]'::jsonb,
    xray_tokens JSONB DEFAULT '[]'::jsonb,
    recommended_action JSONB DEFAULT '{}'::jsonb,
    pipeline_trace JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performant filtering, ordering, and user data isolation
CREATE INDEX IF NOT EXISTS idx_analyses_user_id ON analyses (user_id);
CREATE INDEX IF NOT EXISTS idx_analyses_created_at ON analyses (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_analyses_prediction ON analyses (prediction);
CREATE INDEX IF NOT EXISTS idx_analyses_threat_level ON analyses (threat_level);
CREATE INDEX IF NOT EXISTS idx_analyses_threat_score ON analyses (threat_score);
